#pragma once

#include <Arduino.h>

#define START_BUTTON 2
#define LEFT_PWM 3
#define LEFT_BACK 4
#define LEFT_FORWARD 5
#define STARTER_SIGNAL 6
#define RIGHT_BACK 7
#define RIGHT_FORWARD 8
#define RIGHT_PWM 9
#define SERVO_RIGHT 11 
#define SERVO_LEFT 10 
#define LED_GREEN 13   
#define LED_RED 12   

#define RIGHT_PWM_VALUE 160
#define LEFT_PWM_VALUE 160
#define LEFT_PWM_MAX 255
#define RIGHT_PWM_MAX 255
#define PWM_MAX_DIFFERENCE 0
#define RIGHT_DISTANCE_BORDER 180
#define LEFT_DISTANCE_BORDER 190
#define DISTANCE_BORDER 200
#define DISTANCE_SENSOR_DIFERENCE 26
#define GROUND_DIFFERENCE 700

#define RIGHT_DIST_SENSOR A4
#define RIGHT_GROUND_SENSOR A5
#define LEFT_DIST_SENSOR A6
#define LEFT_GROUND_SENSOR A7
